name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: Nvision-x/shared-workflows/.github/workflows/calver-release.yml@main
