name: 'Terraform'

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         region: 
#           - us-east-1
#           - us-west-1
#           - us-west-2
#           - eu-west-1
#           - eu-central-1
#           - ap-southeast-1
#           - ap-northeast-1
#           # Add more AWS regions as needed
#     name: Scan S3 in ${{ matrix.region }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: AWS

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false

    - name: Upload Buckets CSV as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: s3-buckets
        path: buckets.csv
